name: CI

on:
  push:
    branches:
      # Only run on branch push, not tag push
      - '**'

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      
    - name: Nuget restore
      run: nuget restore HSPI_ZoozControllerLeds.sln
    
    - name: Generate assembly version
      uses: DoctorMcKay/action-csharp-majoryearweekbuild-version@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: MSBuild
      run: |
        msbuild /p:Configuration=Debug /m HSPI_ZoozControllerLeds.sln
        msbuild /p:Configuration=Release /m HSPI_ZoozControllerLeds.sln
        
    - name: Stage artifacts
      run: |
        mkdir artifacts
        cp HSPI_ZoozControllerLeds\bin\Release\HSPI_ZoozControllerLeds.exe artifacts\HSPI_ZoozControllerLeds.exe
        cp HSPI_IRobot\bin\Release\HSPI_ZoozControllerLeds.exe.config artifacts\HSPI_ZoozControllerLeds.exe.config
        cp install.txt artifacts\install.txt
        $release_version = (Get-ChildItem -Filter "artifacts\HSPI_ZoozControllerLeds.exe" | Select-Object -ExpandProperty VersionInfo).FileVersion.Replace('.', '-')
        echo "release_version=$release_version"
        echo "release_version=$release_version" >> $env:GITHUB_ENV
    
    - name: Stage debug artifacts
      run: |
        mkdir artifacts-debug
        cp HSPI_IRobot\bin\Debug\HSPI_ZoozControllerLeds.exe artifacts-debug\HSPI_ZoozControllerLeds.exe
        cp HSPI_IRobot\bin\Debug\HSPI_ZoozControllerLeds.exe.config artifacts-debug\HSPI_ZoozControllerLeds.exe.config
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: iRobot_${{ env.release_version }}
        path: artifacts
    
    - name: Upload debug artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Debug Build
        path: artifacts-debug
